--- 
- name: Starting Deployment
  debug:
    msg: 'OK'

- name: Read credentials from vault
  include_vars: '{{ playbook_dir }}/vars/docker_repo.yml'

- name: Log into remote Nexus repo
  docker_login:
    registry: '{{ nexus_repo_url }}'
    username: '{{ docker_repo_user }}'
    password: '{{ docker_repo_pass }}'
    reauthorize: yes

- name: Redeploy dummy service
  docker_container:
    name: 'dummy-service'
    image: '{{ nexus_repo_url }}/ol_dummy_service'
    state: started
    pull: yes
    recreate: yes
    restart_policy: always

- name: Redeploy nginx config
  template:
    src: {{ playbook_dir }}/lib/templates/nginx/nginx.conf.j2
    dest: nginx.conf  

- name: Redeploy nginx proxy
  docker_container:
    name: 'nginx'
    image: 'nginx:alpine'
    volumes:
      - nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    state: started
    pull: yes
    recreate: yes
    restart_policy: always    

